//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Ad
    {
        public int Id { get; set; }
        public int AD_TYPE_ID { get; set; }
        public string TITLE { get; set; }
        public string DESCRIPTION { get; set; }
        public decimal PRICE { get; set; }
        public bool PUBLISHED { get; set; }
        public int OBJECT_ID { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime ADDITION_DATE { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime EXPIRED_DATE { get; set; }
        public int DISCOUNT_ID { get; set; }
    
        public virtual AD_TYPE AD_TYPE { get; set; }
        public virtual OBJ OBJ { get; set; }
        public virtual DISCOUNT DISCOUNT1 { get; set; }
    }
}
