//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class agencyEntities : DbContext
    {
        public agencyEntities()
            : base("name=agencyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Ad> Ads { get; set; }
        public virtual DbSet<AD_TYPE> AD_TYPE { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<OBJECT_KIND> OBJECT_KIND { get; set; }
        public virtual DbSet<OBJECT_TYPE> OBJECT_TYPE { get; set; }
        public virtual DbSet<OBJ> OBJs { get; set; }
        public virtual DbSet<DISCOUNT> DISCOUNTs { get; set; }
    }
}
