//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agency.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBJ()
        {
            this.Ads = new HashSet<Ad>();
        }
    
        public int Id { get; set; }
        public string ADDRESS { get; set; }
        public double GeoLong { get; set; }
        public double GeoLat { get; set; }
        public Nullable<int> ROOMS { get; set; }
        public int FLOOR { get; set; }
        public int KIND_ID { get; set; }
        public int TYPE_ID { get; set; }
        public string IMAGE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ad> Ads { get; set; }
        public virtual OBJECT_KIND OBJECT_KIND { get; set; }
        public virtual OBJECT_TYPE OBJECT_TYPE { get; set; }
    }
}
